from .patchnr import PatchNR
from .epll import EPLL
from .wcrr import WCRR
from .NETT_prior import NETT
from .tdv import TDV
from .lpn.lpn import LPNPrior
from .local_ar import LocalAR
from .ICNN import ICNNPrior
from .LSR import LSR
from .parameter_learning_wrapper import ParameterLearningWrapper
from .IDCNN_prior import IDCNNPrior
